### ISSUE TITLE
Use in Blazor (wasm)?

### ISSUE THREAD

**Issue by lonix1** [RobThree/NIdenticon#5]
Does someone know how to use this in blazor wasm?

Ideally, to generate the image and insert it into the DOM, without an intermediate image file.

**Comment by lonix1** [comment]
Update:

I tried this, from the examples in the docs page:
````cs
var g = new IdenticonGenerator();
var bitmap = g.Create("foo",);
````

Which fails with:
> System.PlatformNotSupportedException: System.Drawing.Common is not supported on this platform.

**Comment by RobThree** [comment]
You can output a [data-uri](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs); an example of this is [here](https://github.com/RobThree/NIdenticon/blob/master/TestWeb/HtmlHelperExtensions.cs). I haven't had the chance to work with Blazor so I don't know how it would work there but I assume similarly.

As for the `PlatformNotSupportedException`: [this](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) may help:

> ... you can enable support for non-Windows platforms in .NET 6 by setting the `System.Drawing.EnableUnixSupport` [runtime configuration switch](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/) to true in the runtimeconfig.json file.

> _runtimeconfig.template.json template file:_

>
> ```json
> {
>    "configProperties": {
>       "System.Drawing.EnableUnixSupport": true
>    }
> }
> ```

>
> _[appname].runtimeconfig.json output file:_

>
> ```json
> {
>    "runtimeOptions": {
>       "configProperties": {
>          "System.Drawing.EnableUnixSupport": true
>       }
>    }
> }
> ```

**Comment by lonix1** [comment]
Yes I figured out the data-uri bit, but unfortunately the failure occurs before that, when the code enters the `System.Drawing` namespace.

Thanks for that workaround, though I doubt I'd use it if it's targetting Windows... but this bit got my attention:
> It's around 30,000 lines of C code that's largely untested

:open_mouth::open_mouth::open_mouth:
 
That made me laugh! Now I won't feel so bad when I don't write many tests - even MS is guilty!!! :laughing:

PS: if you ever decide to port to blazor, I'll be happy to help test it. :)
